# Generated by Django 5.2.13 on 2026-04-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeadocCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('reply', models.TextField()),
                ('type', models.CharField(max_length=36)),
                ('comment_id', models.IntegerField(db_index=True)),
                ('doc_uuid', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sdoc_comment_reply',
            },
        ),
        migrations.CreateModel(
            name='SeadocDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_uuid', models.CharField(max_length=36, unique=True)),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sdoc_draft',
            },
        ),
        migrations.CreateModel(
            name='SeadocHistoryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_uuid', models.CharField(db_index=True, max_length=36)),
                ('obj_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'history_name',
                'unique_together': {('doc_uuid', 'obj_id')},
            },
        ),
        migrations.CreateModel(
            name='SeadocNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_uuid', models.CharField(max_length=36)),
                ('username', models.CharField(max_length=255)),
                ('msg_type', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detail', models.TextField()),
                ('seen', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sdoc_notification',
                'unique_together': {('doc_uuid', 'username')},
            },
        ),
        migrations.CreateModel(
            name='SeadocRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_uuid', models.CharField(max_length=36, unique=True)),
                ('origin_doc_uuid', models.CharField(db_index=True, max_length=36)),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('revision_id', models.IntegerField()),
                ('origin_doc_path', models.TextField()),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('origin_file_version', models.CharField(max_length=100)),
                ('publish_file_version', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=255, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sdoc_revision',
                'unique_together': {('repo_id', 'revision_id')},
            },
        ),
    ]
