# Generated by Django 5.2.13 on 2026-04-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsAIByOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('month', models.DateField(db_index=True)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'stats_ai_by_owner',
                'unique_together': {('username', 'month', 'model')},
            },
        ),
        migrations.CreateModel(
            name='StatsAIByTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.BigIntegerField()),
                ('month', models.DateField(db_index=True)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'stats_ai_by_team',
                'unique_together': {('org_id', 'month', 'model')},
            },
        ),
    ]
