# Generated by Django 5.2.13 on 2026-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=36, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(db_index=True)),
                ('face_recognition_enabled', models.BooleanField(db_index=True)),
                ('from_commit', models.CharField(max_length=40)),
                ('to_commit', models.CharField(max_length=40)),
                ('tags_enabled', models.BooleanField(db_index=True)),
                ('tags_lang', models.CharField(max_length=36)),
                ('last_face_cluster_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('details_settings', models.TextField()),
                ('ocr_enabled', models.BooleanField(db_index=True)),
                ('global_hidden_columns', models.TextField()),
            ],
            options={
                'db_table': 'repo_metadata',
            },
        ),
        migrations.CreateModel(
            name='RepoMetadataViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'repo_metadata_view',
            },
        ),
    ]
